### ISSUE TITLE
Python 3 Bindings

### ISSUE THREAD

**Issue by njohnsn** [N0NB/hamlib#12]
I'm trying to use hamlib with Python 3.

I cloned the repository from here, but when I try to build it with --with-python-binding I get:

    checking whether to build python binding and demo... yes
    checking whether python3 version is >= 2.1... yes
    checking for python3 version... 3.4
    checking for python3 platform... linux
    checking for python3 script directory... ${prefix}/lib/python3.4/site-packages
    checking for python3 extension module directory... ${exec_prefix}/lib/python3.4/site-packages
    checking for python3.4... /usr/bin/python3.4
    checking for a version of Python >= '2.1.0'... yes
    checking for the distutils Python package... yes
    checking for Python include path... -I/usr/include/python3.4m
    checking for Python library path... -L/usr/lib -lpython3.4m
    checking for Python site-packages path... /usr/lib/python3/dist-packages
    checking python extra libraries... -lrt   -lexpat                   -L/usr/lib -lz  -lexpat -lpthread -ldl  -lutil
    checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking consistency of all components of python development environment... no
    configure: error: in `/home/njohnsn/hamlib':
    configure: error: 
      Could not link test program to Python. Maybe the main Python library has been
      installed in some non-standard library path. If so, pass it to configure,
      via the LDFLAGS environment variable.
      Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
      ============================================================================
      ERROR!
      You probably have to install the development version of the Python package
      for your distribution.  The exact name of this package varies among them.
      ============================================================================

I'm trying to compile on ubuntu 14.04 LTS with stock python 3 (3.4) installed as well as the 3.4 developer package.

Any help would be appreciated.

-Neil

**Comment by airween** [comment]
Hi Neil,

I'm using Linux Mint 17.2 - I think this had been builded on 14.10, but
also had (only) Python 3.4. I have these packages:

$ dpkg -l "*python*" | grep -i dev | grep -i ^ii | awk '{print $2}'
libpython-dev:amd64
libpython2.7-dev:amd64
libpython3.4-dev:amd64
python-dbus-dev
python-dev
python2.7-dev
python3.4-dev

The current Python version is 3.4 on my system:

$ which python
/usr/bin/python
$ ls -la /usr/bin/python
lrwxrwxrwx 1 root root 9 okt   21 20:41 /usr/bin/python -> python3.4
$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

The configure script in my environment on the up-to-date hamlib source can
detects the Python as well:

$ ./configure --with-python-binding
...
checking for Python site-packages path... /usr/lib/python3/dist-packages
checking python extra libraries... -lrt   -lexpat
-L/usr/lib -lz  -lexpat -lpthread -ldl  -lutil
checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1
-Wl,-Bsymbolic-functions
checking consistency of all components of python development environment...
yes
checking Whether to build Tcl bindings and demos... no
...
----------------------------------------------------------------------

 Hamlib Version 3.0~git configuration:

 Prefix         /usr/local
 Preprocessor   gcc -E
 C Compiler     gcc -g -O2
 C++ Compiler   g++

 Package features:
    With C++ binding                no
    With Perl binding               no
    With Python binding             yes
    ...


So, may be you need to check your packages, then your hamlib source version.


73, Ervin
HA2OS

**Comment by njohnsn** [comment]
I installed the packages you listed, and I'm still getting the same error messages, except with the version of python 2.7 listed instead of 3.4

-Neil

**Comment by N0NB** [comment]
* On 2015 24 Oct 17:39 -0500, Neil Johnson wrote:
> I'm trying to use hamlib with Python 3.
> 
> I cloned the repository from here, but when I try to build it with --with-python-binding I get:
> 
>     checking whether to build python binding and demo... yes
>     checking whether python3 version is >= 2.1... yes
>     checking for python3 version... 3.4
>     checking for python3 platform... linux
>     checking for python3 script directory... ${prefix}/lib/python3.4/site-packages
>     checking for python3 extension module directory... ${exec_prefix}/lib/python3.4/site-packages
>     checking for python3.4... /usr/bin/python3.4
>     checking for a version of Python >= '2.1.0'... yes
>     checking for the distutils Python package... yes
>     checking for Python include path... -I/usr/include/python3.4m
>     checking for Python library path... -L/usr/lib -lpython3.4m
>     checking for Python site-packages path... /usr/lib/python3/dist-packages
>     checking python extra libraries... -lrt   -lexpat                   -L/usr/lib -lz  -lexpat -lpthread -ldl  -lutil
>     checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
>     checking consistency of all components of python development environment... no
>     configure: error: in `/home/njohnsn/hamlib':
>     configure: error: 
>       Could not link test program to Python. Maybe the main Python library has been
>       installed in some non-standard library path. If so, pass it to configure,
>       via the LDFLAGS environment variable.
>       Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
>       ============================================================================
>       ERROR!
>       You probably have to install the development version of the Python package
>       for your distribution.  The exact name of this package varies among them.
>       ============================================================================
> 
> I'm trying to compile on ubuntu 14.04 LTS with stock python 3 (3.4) installed as well as the 3.4 developer package.

Hi Neil.

So far I have not tried building the Python binding on a system where
Python3 is the default.  When you do 'python -V' what is the version
returned?  On my system--Debian Jessie--I receive "Python 2.7.9".

There is extra information in the config.log file.  You can grep for the
line that has "checking whether to build python binding and demo" and
look at the following lines.  Mine looks like this:

configure:18343: checking whether to build python binding and demo
configure:18353: result: yes
configure:18393: checking for a Python interpreter with version >= 2.1
configure:18410: python -c import sys # split strings by '.' and convert
to numeric. Append some zeros # because we need at least 4 digits for the hex
conversion. # map returns an iterator in Python 3.0 and a list in 2.x minver =
list(map(int, '2.1'.split('.'))) + [0, 0, 0] minverhex = 0 # xrange is not present
in Python 3.0 and range returns an iterator for i in list(range(0, 4)):
minverhex = (minverhex << 8) + minver[i] sys.exit(sys.hexversion < minverhex)
configure:18413: $? = 0
configure:18419: result: python
configure:18427: checking for python
configure:18445: found /usr/bin/python
configure:18457: result: /usr/bin/python
configure:18475: checking for python version
configure:18482: result: 2.7
configure:18494: checking for python platform
configure:18501: result: linux2
configure:18527: checking for python script directory
configure:18562: result: ${prefix}/lib/python2.7/site-packages
configure:18571: checking for python extension module directory
configure:18606: result: ${exec_prefix}/lib/python2.7/site-packages
configure:18627: checking for python2.7
configure:18657: result: /usr/bin/python
configure:18673: checking for a version of Python >= '2.1.0'
configure:18699: result: yes
configure:18730: checking for the distutils Python package
configure:18734: result: yes
configure:18748: checking for Python include path
configure:18764: result: -I/usr/include/python2.7
configure:18771: checking for Python library path
configure:18848: result: -L/usr/lib -lpython2.7
configure:18855: checking for Python site-packages path
configure:18861: result: /usr/lib/python2.7/dist-packages
configure:18868: checking python extra libraries
configure:18875: result: -L/usr/lib -lz -lpthread -ldl  -lutil
configure:18882: checking python extra linking flags
configure:18889: result: -Xlinker -export-dynamic -Wl,-O1
-Wl,-Bsymbolic-functions
configure:18896: checking consistency of all components of python
development environment
configure:18922: gcc -o conftest -g -O2   -I/usr/include/python2.7
conftest.c -L/usr/lib -lpython2.7 -Xlinker -export-dynamic -Wl,-O1
-Wl,-Bsymbolic-functions  -L/usr/lib -lz -lpthread -ldl  -lutil >&5
configure:18922: $? = 0
configure:18939: result: yes

In particular, the line where gcc is called to compile conftest.c may be
the most helpful.

> Any help would be appreciated.

If we hit a roadblock, the Ubuntu Hams mailing list may have someone
more familiar with Python3 as the default.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by airween** [comment]
Hi Neil,

you can check this error at this way:

$ cat << EOF > conftest.c
#include <Python.h>
int
main ()
{
Py_Initialize();
  ;
  return 0;
}

EOF

and then

$ gcc -Wall -o conftest -g -O2 -I/usr/include/python3.4m conftest.c -L/usr/lib -lpython3.4m -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -lrt -lexpat -L/usr/lib -lz -lexpat -lpthread -ldl  -lutil

Please copy here your output.


73, Ervin
HA2OS

**Comment by njohnsn** [comment]
If I try to compile your test program I get:

    /usr/bin/ld: cannot find -lz
    collect2: error: ld returned 1 exit status

**Comment by njohnsn** [comment]
Looks like I was missing the zlib1g-dev package. Unfortunately I have to rebuild my ubuntu VM to get back to python3 default. I'll keep you posted. Thanks for your help!

**Comment by airween** [comment]
Neil,

I think that weren't you miss the zlib1g-dev package - in my opinion, the package maintainer should have set the dependencies, because Python contains the necessary libs:
`python3.4 -c "from distutils import sysconfig; print(sysconfig.get_config_var('MODLIBS'))"`
will gives
`-lrt   -lexpat                   -L/usr/lib -lz  -lexpat`

Well, I'm happy that hamlib works on your system :)

**Comment by njohnsn** [comment]
Got it to build. Thanks for all your help!

**Comment by N0NB** [comment]
* On 2015 28 Oct 20:17 -0500, Neil Johnson wrote:
> Got it to build. Thanks for all your help!

Good to hear, Neil.

Please send a summary of what you did that resolved the issue so it can
be closed.

Thanks!

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us
